### PR TITLE
Component Discovery With Reclass

### LINKED ISSUE #138: Fake Components During Discovery
## Context
During discovery, all components are being cloned, even ones that are not included for the current cluster. Faking the components in this step could improve performance a lot. Additionally would it lower the side effects components can have to each other. 
After the inventory is built, the actually included components of a cluster can be cloned.

### PR DESCRIPTION
**Pull request by srueg**
One consequence of this is, that the hierarchy can't reference parameters which are defined in component classes (i.e. defaults). This is due to the fact that a reclass inventory must be able to resolve all references in order to be rendered. There's no mechanism to ignore invalid references (like there is for ignoring inexistent class files). 

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Update the ./CHANGELOG.md.
- [x] Link this PR to related issues.

Closes #138

### CODE REVIEW

**Comment by Kidswiss** [comment]
As from today's sync:

Tested to access a puppet profile variable in hiera, it doesn't seem to be working.

**Review by corvus-ch — APPROVED** [review]

**Review by simu — APPROVED** [review]

**Comment by tobru** [comment]
Please also make sure that this is documented, maybe needs to be done after #147 has been merged.

**Comment by srueg** [comment]
As discussed during the SYNc today: Since this is also not allowed in Puppet and it's probably better that way anyway, we'll proceed with this approach and from now on don't allow parameters which are set in components to be referenced from the inventory.

**Comment by simu** [comment]
Currently testing this for some "common" usecases. What I found so far is that with this approach we'll have to rethink how local mode works, as you now can't just add a component in the inventory somewhere and run `catalog compile --local` to inspect the changes.

**Comment by srueg** [comment]
I don't think I understand the problem. This wasn't possible before either?

**Comment by simu** [comment]
It is currently possible for any component that the file-based discovery mechanism finds and downloads.

**Review by simu — APPROVED** [review]

**Review by tobru — APPROVED** [review]

**Pull request merged**
