### PR TITLE
Upgrade to Kapitan v0.30

### PR DESCRIPTION
**Pull request by simu**
Kapitan 0.30 requires Python 3.7+, so we're dropping support for 3.6 in this PR.

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Update the documentation.
- [x] Update tests.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog
- [x] ~~Upgrade Kapitan to v0.30.0 from prerelease version~~ will be done in a follow-up PR
- [x] Remove remaining code for building and deploying Helm bindings
- [x] Update integration test to render a component which uses a Helm chart

### CODE REVIEW

**Comment by laserb** [comment]
Please remove https://github.com/projectsyn/commodore/blob/master/pyproject.toml#L17 , https://github.com/projectsyn/commodore/blob/master/pyproject.toml#L47 , https://github.com/projectsyn/commodore/blame/master/README.md#L46  and https://github.com/projectsyn/commodore/blob/master/commodore/copy_helm_bindings.py
as it should not be needed anymore.

**Comment by simu** [comment]
> Please remove https://github.com/projectsyn/commodore/blob/master/pyproject.toml#L17 , https://github.com/projectsyn/commodore/blob/master/pyproject.toml#L47 , https://github.com/projectsyn/commodore/blame/master/README.md#L46 and https://github.com/projectsyn/commodore/blob/master/commodore/copy_helm_bindings.py
> as it should not be needed anymore.

Yes, it's already there as a bullet point in the PR: 

>  Remove remaining code for building and deploying Helm bindings

**Review by bastjan — APPROVED** [review]
LGTM 🚀

I'm no python expert but the code looks good and the upgrade/migration instructions look clear to me. Also works on macOS with M1 chip! 🥳

**Review by corvus-ch — APPROVED** [review]

**Comment by simu** [comment]
Final round of testing:
* Docker image built from this branch works as expected (incl. fetching and rendering Helm charts using `helm3`)
* Smart diffing of removed `null` objects slightly improved in https://github.com/projectsyn/commodore/pull/358/commits/af21245996b9b900b8b9ddd18e9a1983c96be365

**Pull request merged**
