### PR TITLE
Rename component template GitHub workflow config to test.yml

### PR DESCRIPTION
**Pull request by simu**
Apparently GitHub won't pick up workflows defined in files with extension .yaml.

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Update the ./CHANGELOG.md.

### CODE REVIEW

**Comment by srueg** [comment]
I don't think that's the issue. As from the documentation:
> Workflow files use YAML syntax, and must have either a .yml or .yaml file extension
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows

**Comment by simu** [comment]
Well, for sure the actions did not work when the file was named `test.yaml`, and started working immediately when I renamed it (e.g. on projectsyn/component-fluentbit)

**Comment by simu** [comment]
Hmm, looks like it may be unrelated to the file name but it appears that GitHub only detects the file after it's renamed or something, cf. https://github.community/t/no-github-actions-workflows-detected-in-repo/16085

**Comment by simu** [comment]
The file name is not the issue for workflows sometimes not being picked up. Closing this PR.

**Pull request closed without merging**
